export default [
  // ========== ACTION ==========
  { title: "Aim Trainer", slug: "aim-trainer", description: "Click targets as fast as you can. 30-second rounds with accuracy tracking.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap the targets", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/aim-trainer/index.html" },
  { title: "Balloon Pop", slug: "balloon-pop", description: "Pop balloons before they float away. 60-second rounds.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap balloons to pop them", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/balloon-pop/index.html" },
  { title: "Color Match", slug: "color-match", description: "Does the word match the ink color? Test your reflexes in 30-second rounds.", category: "action", tags: ["reflex", "colors", "timed"], difficulty: "easy", controls: "Click Match/No Match or press Y/N keys", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/color-match/index.html" },
  { title: "Doodle Jump", slug: "doodle-jump", description: "Bounce upward on platforms. How high can you go?", category: "action", tags: ["endless", "platformer"], difficulty: "medium", controls: "Arrow keys or tilt to move, auto-bounce", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/doodle-jump/index.html" },
  { title: "Flappy Bird", slug: "flappy-bird", description: "Tap to flap and navigate through pipes without crashing.", category: "action", tags: ["reflex", "endless"], difficulty: "medium", controls: "Click, tap, or press Space to flap", mobileSupport: true, dateAdded: "2026-04-04", featured: true, gamePath: "/games/_src/flappy-bird/index.html" },
  { title: "Maze Runner", slug: "maze-runner", description: "Find your way through a randomly generated maze as fast as you can.", category: "action", tags: ["maze", "timed"], difficulty: "medium", controls: "Arrow keys or swipe to move", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/maze-runner/index.html" },
  { title: "Piano Tiles", slug: "piano-tiles", description: "Tap the black tiles as they scroll down. Miss one and it's over.", category: "action", tags: ["rhythm", "reflex"], difficulty: "medium", controls: "Tap tiles or press D/F/J/K keys", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/piano-tiles/index.html" },
  { title: "Reaction Time", slug: "reaction-time", description: "Test how fast you can click when the screen turns green. Best of 5.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap when the screen turns green", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/reaction-time/index.html" },
  { title: "Tower Stack", slug: "tower-stack", description: "Stack sliding blocks as high as you can. Overhanging parts get cut off.", category: "action", tags: ["timing", "endless"], difficulty: "medium", controls: "Click, tap, or press Space to drop the block", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/tower-stack/index.html" },
  { title: "Whack-a-Mole", slug: "whack-a-mole", description: "Whack the moles as they pop up from their holes. 30-second rounds.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap the moles", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/whack-a-mole/index.html" },

  // ========== ARCADE ==========
  { title: "Asteroids", slug: "asteroids", description: "Rotate, thrust, and shoot asteroids before they hit your ship.", category: "arcade", tags: ["classic", "shooter"], difficulty: "medium", controls: "Arrow keys to move, Space to shoot. Touch controls on mobile.", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/asteroids/index.html" },
  { title: "Breakout", slug: "breakout", description: "Bounce a ball off a paddle to break all the bricks.", category: "arcade", tags: ["classic", "ball"], difficulty: "easy", controls: "Mouse or arrow keys to move paddle", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/breakout/index.html" },
  { title: "Pong", slug: "pong", description: "Classic paddle game. Play against the computer. First to 5 wins.", category: "arcade", tags: ["classic", "paddle"], difficulty: "easy", controls: "Arrow keys or touch buttons to move paddle", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/pong/index.html" },
  { title: "Snake", slug: "snake", description: "Guide the snake to eat food and grow longer without hitting walls or yourself.", category: "arcade", tags: ["classic", "reflex"], difficulty: "easy", controls: "Arrow keys or WASD to change direction", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/snake/index.html" },
  { title: "Space Invaders", slug: "space-invaders", description: "Defend Earth from waves of descending aliens. Classic arcade shooter.", category: "arcade", tags: ["classic", "shooter"], difficulty: "medium", controls: "Arrow keys to move, Space to shoot. Touch controls on mobile.", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/space-invaders/index.html" },

  // ========== BOARD ==========
  { title: "Checkers", slug: "checkers", description: "Classic checkers game. Jump over your opponent's pieces to capture them and win.", category: "board", tags: ["classic", "two-player"], difficulty: "medium", controls: "Click a piece, then click a valid square to move", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/checkers/index.html" },
  { title: "Connect Four", slug: "connect-four", description: "Drop discs into columns to connect four in a row before your opponent does.", category: "board", tags: ["classic", "two-player"], difficulty: "easy", controls: "Click a column to drop your disc", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/connect-four/index.html" },
  { title: "Dice Roller", slug: "dice-roller", description: "Roll up to 6 dice with 3D animation. Track history and statistics.", category: "board", tags: ["dice", "tool"], difficulty: "easy", controls: "Click Roll or press Space", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/dice-roller/index.html" },
  { title: "Reversi", slug: "reversi", description: "Place pieces to flip your opponent's. Whoever has more pieces wins.", category: "board", tags: ["classic", "strategy"], difficulty: "medium", controls: "Click a valid cell to place your piece", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/reversi/index.html" },
  { title: "Tic-Tac-Toe", slug: "tic-tac-toe", description: "Classic three-in-a-row game. Play against a friend or challenge the computer.", category: "board", tags: ["classic", "two-player"], difficulty: "easy", controls: "Click or tap to place your mark", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/tic-tac-toe/index.html" },

  // ========== CARD ==========
  { title: "Solitaire", slug: "solitaire", description: "Classic Klondike solitaire. Sort all cards into four foundation piles by suit.", category: "card", tags: ["classic", "patience"], difficulty: "medium", controls: "Click and drag cards to move them", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/solitaire/index.html" },

  // ========== PUZZLE ==========
  { title: "2048", slug: "2048", description: "Slide numbered tiles on a grid to combine them and reach the 2048 tile.", category: "puzzle", tags: ["numbers", "sliding"], difficulty: "medium", controls: "Arrow keys or swipe to slide tiles", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/2048/index.html" },
  { title: "Crossword Mini", slug: "crossword-mini", description: "Solve a small 5x5 crossword puzzle from built-in clues.", category: "puzzle", tags: ["words", "logic"], difficulty: "medium", controls: "Click a cell and type letters. Tab to toggle direction.", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/crossword-mini/index.html" },
  { title: "Lights Out", slug: "lights-out", description: "Toggle lights on a 5x5 grid. Clicking one toggles its neighbors. Turn all off to win.", category: "puzzle", tags: ["logic", "grid"], difficulty: "medium", controls: "Click or tap a light to toggle it and its neighbors", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/lights-out/index.html" },
  { title: "Memory Match", slug: "memory-match", description: "Flip cards to find matching pairs. Track your moves and time.", category: "puzzle", tags: ["memory", "cards"], difficulty: "easy", controls: "Click or tap cards to flip them", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/memory-match/index.html" },
  { title: "Minesweeper", slug: "minesweeper", description: "Reveal squares on a grid without detonating hidden mines.", category: "puzzle", tags: ["classic", "logic"], difficulty: "medium", controls: "Left click to reveal, right click to flag", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/minesweeper/index.html" },
  { title: "Number Guess", slug: "number-guess", description: "Guess the number between 1 and 100. Higher or lower hints after each guess.", category: "puzzle", tags: ["logic", "numbers"], difficulty: "easy", controls: "Type a number and press Enter or click Guess", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/number-guess/index.html" },
  { title: "Simon Says", slug: "simon-says", description: "Watch the color sequence, then repeat it. Each round adds one more step.", category: "puzzle", tags: ["memory", "sequence"], difficulty: "easy", controls: "Click or tap the colored buttons", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/simon-says/index.html" },
  { title: "Sliding Puzzle", slug: "sliding-puzzle", description: "Slide numbered tiles into the correct order on a 4x4 grid.", category: "puzzle", tags: ["logic", "sliding"], difficulty: "medium", controls: "Click a tile next to the empty space, or use arrow keys", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/sliding-puzzle/index.html" },
  { title: "Sudoku", slug: "sudoku", description: "Fill the 9x9 grid so every row, column, and box contains 1 through 9.", category: "puzzle", tags: ["logic", "numbers"], difficulty: "hard", controls: "Click a cell and type a number, or use the number pad", mobileSupport: true, dateAdded: "2026-04-04", featured: true, gamePath: "/games/_src/sudoku/index.html" },
  { title: "Tetris Clone", slug: "tetris-clone", description: "Classic falling blocks puzzle game. Clear lines to score points and level up.", category: "puzzle", tags: ["classic", "falling-blocks"], difficulty: "easy", controls: "Arrow keys to move, Up to rotate, Space to hard drop", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/tetris-clone/index.html" },

  // ========== RACING ==========
  { title: "Car Dodge", slug: "car-dodge", description: "Dodge oncoming cars on a 3-lane road. Speed increases over time.", category: "racing", tags: ["reflex", "endless"], difficulty: "easy", controls: "Arrow keys or swipe to switch lanes", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/car-dodge/index.html" },

  // ========== SIMULATION ==========
  { title: "Brick Builder", slug: "brick-builder", description: "Place colored bricks on a grid to build whatever you want.", category: "simulation", tags: ["creative", "sandbox"], difficulty: "easy", controls: "Click to place bricks, choose colors from the palette", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/brick-builder/index.html" },
  { title: "Cookie Clicker", slug: "cookie-clicker", description: "Click cookies, buy upgrades, automate production.", category: "simulation", tags: ["idle", "incremental"], difficulty: "easy", controls: "Click the cookie, then buy upgrades", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/cookie-clicker/index.html" },
  { title: "Etch a Sketch", slug: "etch-a-sketch", description: "Draw on a canvas with arrow keys or touch. Pick colors and shake to clear.", category: "simulation", tags: ["creative", "drawing"], difficulty: "easy", controls: "Arrow keys or drag to draw. Color picker and shake button.", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/etch-a-sketch/index.html" },

  // ========== STRATEGY ==========
  { title: "Rock Paper Scissors", slug: "rock-paper-scissors", description: "Best of 5 against the computer. Classic hand game.", category: "strategy", tags: ["classic", "quick"], difficulty: "easy", controls: "Click or tap your choice", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/rock-paper-scissors/index.html" },

  // ========== WORD ==========
  { title: "Hangman", slug: "hangman", description: "Guess the word one letter at a time before the hangman is complete.", category: "word", tags: ["classic", "guessing"], difficulty: "easy", controls: "Click letters or type on keyboard", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/hangman/index.html" },
  { title: "Trivia Quiz", slug: "trivia-quiz", description: "Answer 10 multiple choice questions from a bank of 30+.", category: "word", tags: ["trivia", "knowledge"], difficulty: "medium", controls: "Click or tap an answer", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/trivia-quiz/index.html" },
  { title: "Typing Speed", slug: "typing-speed", description: "Type as many words as you can in 60 seconds. Tracks WPM and accuracy.", category: "word", tags: ["typing", "timed"], difficulty: "medium", controls: "Type the displayed words on your keyboard", mobileSupport: false, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/typing-speed/index.html" },
  { title: "Word Scramble", slug: "word-scramble", description: "Unscramble the letters to form a valid word before time runs out.", category: "word", tags: ["vocabulary", "timed"], difficulty: "medium", controls: "Type letters on keyboard or click letter tiles", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/word-scramble/index.html" },
];
