export default [
  // ========== ACTION ==========
  { title: "Aim Trainer", slug: "aim-trainer", description: "Click targets as fast as you can. 30-second rounds.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap the targets", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/aim-trainer/index.html" },
  { title: "Balloon Pop", slug: "balloon-pop", description: "Pop balloons before they float away. 60-second rounds.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap balloons to pop them", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/balloon-pop/index.html" },
  { title: "Color Match", slug: "color-match", description: "Does the word match the ink color? 30-second rounds.", category: "action", tags: ["reflex", "colors"], difficulty: "easy", controls: "Click Match/No Match or press Y/N", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/color-match/index.html" },
  { title: "Doodle Jump", slug: "doodle-jump", description: "Bounce upward on platforms. How high can you go?", category: "action", tags: ["endless", "platformer"], difficulty: "medium", controls: "Arrow keys or tilt to move", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/doodle-jump/index.html" },
  { title: "Flappy Bird", slug: "flappy-bird", description: "Tap to flap through pipes without crashing.", category: "action", tags: ["reflex", "endless"], difficulty: "medium", controls: "Click, tap, or Space to flap", mobileSupport: true, dateAdded: "2026-04-04", featured: true, gamePath: "/games/_src/flappy-bird/index.html" },
  { title: "Maze Runner", slug: "maze-runner", description: "Navigate a randomly generated maze.", category: "action", tags: ["maze", "timed"], difficulty: "medium", controls: "Arrow keys or swipe", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/maze-runner/index.html" },
  { title: "Piano Tiles", slug: "piano-tiles", description: "Tap the black tiles as they scroll. Miss one and it's over.", category: "action", tags: ["rhythm", "reflex"], difficulty: "medium", controls: "Tap tiles or D/F/J/K keys", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/piano-tiles/index.html" },
  { title: "Reaction Time", slug: "reaction-time", description: "Click when the screen turns green. Best of 5.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap when green", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/reaction-time/index.html" },
  { title: "Tower Stack", slug: "tower-stack", description: "Stack sliding blocks. Overhanging parts get cut.", category: "action", tags: ["timing", "endless"], difficulty: "medium", controls: "Click, tap, or Space to drop", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/tower-stack/index.html" },
  { title: "Whack-a-Mole", slug: "whack-a-mole", description: "Whack moles as they pop up. 30-second rounds.", category: "action", tags: ["reflex", "timed"], difficulty: "easy", controls: "Click or tap the moles", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/whack-a-mole/index.html" },

  // ========== ARCADE ==========
  { title: "Asteroids", slug: "asteroids", description: "Shoot asteroids before they hit your ship.", category: "arcade", tags: ["classic", "shooter"], difficulty: "medium", controls: "Arrows to move, Space to shoot", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/asteroids/index.html" },
  { title: "Breakout", slug: "breakout", description: "Bounce a ball off a paddle to break bricks.", category: "arcade", tags: ["classic", "ball"], difficulty: "easy", controls: "Mouse or arrows to move paddle", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/breakout/index.html" },
  { title: "Pong", slug: "pong", description: "Paddle game vs computer. First to 5 wins.", category: "arcade", tags: ["classic", "paddle"], difficulty: "easy", controls: "Arrow keys or touch buttons", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/pong/index.html" },
  { title: "Snake", slug: "snake", description: "Eat food and grow without hitting walls or yourself.", category: "arcade", tags: ["classic", "reflex"], difficulty: "easy", controls: "Arrow keys or WASD", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/snake/index.html" },
  { title: "Space Invaders", slug: "space-invaders", description: "Defend Earth from waves of descending aliens.", category: "arcade", tags: ["classic", "shooter"], difficulty: "medium", controls: "Arrows to move, Space to shoot", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/space-invaders/index.html" },

  // ========== BOARD ==========
  { title: "Battleship", slug: "battleship", description: "Find and sink the enemy fleet on a 10x10 grid.", category: "board", tags: ["classic", "strategy"], difficulty: "medium", controls: "Click to place ships and fire", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/battleship/index.html" },
  { title: "Checkers", slug: "checkers", description: "Jump and capture opponent pieces to win.", category: "board", tags: ["classic", "two-player"], difficulty: "medium", controls: "Click piece, then click destination", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/checkers/index.html" },
  { title: "Connect Four", slug: "connect-four", description: "Drop discs to connect four in a row.", category: "board", tags: ["classic", "two-player"], difficulty: "easy", controls: "Click a column to drop", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/connect-four/index.html" },
  { title: "Dice Roller", slug: "dice-roller", description: "Roll dice with 3D animation. Track stats.", category: "board", tags: ["dice", "tool"], difficulty: "easy", controls: "Click Roll or press Space", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/dice-roller/index.html" },
  { title: "Reversi", slug: "reversi", description: "Place pieces to flip your opponent's. Most pieces wins.", category: "board", tags: ["classic", "strategy"], difficulty: "medium", controls: "Click a valid cell", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/reversi/index.html" },
  { title: "Tic-Tac-Toe", slug: "tic-tac-toe", description: "Three in a row. Play against computer or a friend.", category: "board", tags: ["classic", "two-player"], difficulty: "easy", controls: "Click or tap to place mark", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/tic-tac-toe/index.html" },

  // ========== CARD ==========
  { title: "Blackjack", slug: "blackjack", description: "Hit, stand, or double down. Beat the dealer to 21.", category: "card", tags: ["classic", "casino"], difficulty: "easy", controls: "Click Hit, Stand, or Double Down", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/blackjack/index.html" },
  { title: "Solitaire", slug: "solitaire", description: "Sort cards into foundation piles by suit.", category: "card", tags: ["classic", "patience"], difficulty: "medium", controls: "Click and drag cards", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/solitaire/index.html" },
  { title: "War", slug: "war", description: "Flip cards — higher rank wins. Collect the whole deck.", category: "card", tags: ["classic", "simple"], difficulty: "easy", controls: "Click to flip cards", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/war/index.html" },

  // ========== PUZZLE ==========
  { title: "2048", slug: "2048", description: "Slide tiles to combine and reach 2048.", category: "puzzle", tags: ["numbers", "sliding"], difficulty: "medium", controls: "Arrow keys or swipe", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/2048/index.html" },
  { title: "Crossword Mini", slug: "crossword-mini", description: "Solve a small 5x5 crossword puzzle.", category: "puzzle", tags: ["words", "logic"], difficulty: "medium", controls: "Click cell and type letters", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/crossword-mini/index.html" },
  { title: "Jigsaw Mini", slug: "jigsaw-mini", description: "Swap pieces to put a 4x4 grid in order.", category: "puzzle", tags: ["logic", "spatial"], difficulty: "easy", controls: "Click two pieces to swap", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/jigsaw-mini/index.html" },
  { title: "Lights Out", slug: "lights-out", description: "Toggle lights to turn them all off.", category: "puzzle", tags: ["logic", "grid"], difficulty: "medium", controls: "Click a light to toggle neighbors", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/lights-out/index.html" },
  { title: "Match Three", slug: "match-three", description: "Swap gems to match 3 in a row. 60-second rounds.", category: "puzzle", tags: ["matching", "timed"], difficulty: "easy", controls: "Click two adjacent gems to swap", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/match-three/index.html" },
  { title: "Memory Match", slug: "memory-match", description: "Flip cards to find matching pairs.", category: "puzzle", tags: ["memory", "cards"], difficulty: "easy", controls: "Click or tap cards", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/memory-match/index.html" },
  { title: "Minesweeper", slug: "minesweeper", description: "Reveal squares without hitting mines.", category: "puzzle", tags: ["classic", "logic"], difficulty: "medium", controls: "Left click reveal, right click flag", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/minesweeper/index.html" },
  { title: "Nonogram", slug: "nonogram", description: "Fill grid cells based on number clues.", category: "puzzle", tags: ["logic", "grid"], difficulty: "medium", controls: "Click to fill, right-click to mark X", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/nonogram/index.html" },
  { title: "Number Guess", slug: "number-guess", description: "Guess 1-100 with higher/lower hints.", category: "puzzle", tags: ["logic", "numbers"], difficulty: "easy", controls: "Type a number and press Enter", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/number-guess/index.html" },
  { title: "Simon Says", slug: "simon-says", description: "Repeat the growing color sequence.", category: "puzzle", tags: ["memory", "sequence"], difficulty: "easy", controls: "Click the colored buttons", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/simon-says/index.html" },
  { title: "Sliding Puzzle", slug: "sliding-puzzle", description: "Slide tiles into the correct order.", category: "puzzle", tags: ["logic", "sliding"], difficulty: "medium", controls: "Click tile or use arrow keys", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/sliding-puzzle/index.html" },
  { title: "Sudoku", slug: "sudoku", description: "Fill the 9x9 grid — every row, column, box gets 1-9.", category: "puzzle", tags: ["logic", "numbers"], difficulty: "hard", controls: "Click cell and type number", mobileSupport: true, dateAdded: "2026-04-04", featured: true, gamePath: "/games/_src/sudoku/index.html" },
  { title: "Tetris Clone", slug: "tetris-clone", description: "Clear lines with falling blocks.", category: "puzzle", tags: ["classic", "falling-blocks"], difficulty: "easy", controls: "Arrows to move, Up to rotate, Space to drop", mobileSupport: true, dateAdded: "2026-04-03", featured: true, gamePath: "/games/_src/tetris-clone/index.html" },

  // ========== RACING ==========
  { title: "Bike Lane", slug: "bike-lane", description: "Side-scrolling cyclist. Jump over obstacles.", category: "racing", tags: ["endless", "reflex"], difficulty: "easy", controls: "Space or tap to jump", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/bike-lane/index.html" },
  { title: "Car Dodge", slug: "car-dodge", description: "Dodge oncoming cars on a 3-lane road.", category: "racing", tags: ["reflex", "endless"], difficulty: "easy", controls: "Arrows or swipe to switch lanes", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/car-dodge/index.html" },
  { title: "Drag Race", slug: "drag-race", description: "Reaction launch and gear shifting. Quarter mile.", category: "racing", tags: ["reaction", "timing"], difficulty: "medium", controls: "Tap/click at green light, shift at right RPM", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/drag-race/index.html" },

  // ========== SIMULATION ==========
  { title: "Brick Builder", slug: "brick-builder", description: "Place colored bricks to build anything.", category: "simulation", tags: ["creative", "sandbox"], difficulty: "easy", controls: "Click to place, pick colors", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/brick-builder/index.html" },
  { title: "Cookie Clicker", slug: "cookie-clicker", description: "Click cookies, buy upgrades, automate.", category: "simulation", tags: ["idle", "incremental"], difficulty: "easy", controls: "Click cookie, buy upgrades", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/cookie-clicker/index.html" },
  { title: "Etch a Sketch", slug: "etch-a-sketch", description: "Draw with arrows or touch. Shake to clear.", category: "simulation", tags: ["creative", "drawing"], difficulty: "easy", controls: "Arrow keys or drag to draw", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/etch-a-sketch/index.html" },
  { title: "Fish Tank", slug: "fish-tank", description: "Feed fish, earn coins, grow your aquarium.", category: "simulation", tags: ["idle", "virtual-pet"], difficulty: "easy", controls: "Click to drop food, buy fish", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/fish-tank/index.html" },
  { title: "Lemonade Stand", slug: "lemonade-stand", description: "Set prices and supply based on weather. Maximize profit.", category: "simulation", tags: ["business", "strategy"], difficulty: "easy", controls: "Set price and cups, click Start Day", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/lemonade-stand/index.html" },

  // ========== SPORTS ==========
  { title: "Basketball", slug: "basketball", description: "Aim and shoot free throws. 60-second rounds.", category: "sports", tags: ["aim", "timed"], difficulty: "easy", controls: "Click/drag to aim and set power", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/basketball/index.html" },
  { title: "Golf Putt", slug: "golf-putt", description: "Top-down mini golf. Aim, set power, sink the putt.", category: "sports", tags: ["aim", "precision"], difficulty: "medium", controls: "Click and drag to aim and set power", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/golf-putt/index.html" },
  { title: "Penalty Kicks", slug: "penalty-kicks", description: "Pick a zone to shoot. Keeper dives randomly. Best of 5.", category: "sports", tags: ["quick", "aim"], difficulty: "easy", controls: "Click a zone on the goal", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/penalty-kicks/index.html" },

  // ========== STRATEGY ==========
  { title: "Rock Paper Scissors", slug: "rock-paper-scissors", description: "Best of 5 against the computer.", category: "strategy", tags: ["classic", "quick"], difficulty: "easy", controls: "Click your choice", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/rock-paper-scissors/index.html" },
  { title: "Tower Defense", slug: "tower-defense", description: "Place towers to stop enemies. 10 waves.", category: "strategy", tags: ["tower-defense", "tactical"], difficulty: "medium", controls: "Click to place towers", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/tower-defense/index.html" },

  // ========== WORD ==========
  { title: "Hangman", slug: "hangman", description: "Guess the word letter by letter.", category: "word", tags: ["classic", "guessing"], difficulty: "easy", controls: "Click letters or type", mobileSupport: true, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/hangman/index.html" },
  { title: "Trivia Quiz", slug: "trivia-quiz", description: "10 multiple choice questions from 30+.", category: "word", tags: ["trivia", "knowledge"], difficulty: "medium", controls: "Click an answer", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/trivia-quiz/index.html" },
  { title: "Typing Speed", slug: "typing-speed", description: "Type words in 60 seconds. Tracks WPM.", category: "word", tags: ["typing", "timed"], difficulty: "medium", controls: "Type on keyboard", mobileSupport: false, dateAdded: "2026-04-04", featured: false, gamePath: "/games/_src/typing-speed/index.html" },
  { title: "Word Scramble", slug: "word-scramble", description: "Unscramble letters before time runs out.", category: "word", tags: ["vocabulary", "timed"], difficulty: "medium", controls: "Type or click letter tiles", mobileSupport: true, dateAdded: "2026-04-03", featured: false, gamePath: "/games/_src/word-scramble/index.html" },
  { title: "Word Search", slug: "word-search", description: "Find 6 hidden words in a 10x10 letter grid.", category: "word", tags: ["search", "visual"], difficulty: "easy", controls: "Click and drag to select words", mobileSupport: true, dateAdded: "2026-04-05", featured: false, gamePath: "/games/_src/word-search/index.html" },
  { title: "Wordle Clone", slug: "wordle-clone", description: "Guess the 5-letter word in 6 tries.", category: "word", tags: ["logic", "guessing"], difficulty: "medium", controls: "Type a word and press Enter", mobileSupport: true, dateAdded: "2026-04-05", featured: true, gamePath: "/games/_src/wordle-clone/index.html" },
];
