export default [
  // ========== ACTION ==========
  {
    title: "Color Match",
    slug: "color-match",
    description: "Does the word match the ink color? Test your reflexes in 30-second rounds.",
    category: "action",
    tags: ["reflex", "colors", "timed"],
    thumbnail: "/assets/img/games/color-match.jpg",
    difficulty: "easy",
    controls: "Click Match/No Match or press Y/N keys",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/color-match/index.html",
  },
  {
    title: "Flappy Bird",
    slug: "flappy-bird",
    description: "Tap to flap and navigate through pipes without crashing.",
    category: "action",
    tags: ["reflex", "endless", "single-player"],
    thumbnail: "/assets/img/games/flappy-bird.jpg",
    difficulty: "medium",
    controls: "Click, tap, or press Space to flap",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: true,
    gamePath: "/games/_src/flappy-bird/index.html",
  },
  {
    title: "Maze Runner",
    slug: "maze-runner",
    description: "Find your way through a randomly generated maze as fast as you can.",
    category: "action",
    tags: ["maze", "timed", "single-player"],
    thumbnail: "/assets/img/games/maze-runner.jpg",
    difficulty: "medium",
    controls: "Arrow keys or swipe to move",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/maze-runner/index.html",
  },
  {
    title: "Whack-a-Mole",
    slug: "whack-a-mole",
    description: "Whack the moles as they pop up from their holes. 30-second rounds.",
    category: "action",
    tags: ["reflex", "timed", "single-player"],
    thumbnail: "/assets/img/games/whack-a-mole.jpg",
    difficulty: "easy",
    controls: "Click or tap the moles",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/whack-a-mole/index.html",
  },

  // ========== ARCADE ==========
  {
    title: "Breakout",
    slug: "breakout",
    description: "Bounce a ball off a paddle to break all the bricks. Classic arcade action.",
    category: "arcade",
    tags: ["classic", "ball", "single-player"],
    thumbnail: "/assets/img/games/breakout.jpg",
    difficulty: "easy",
    controls: "Mouse or arrow keys to move paddle",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: false,
    gamePath: "/games/_src/breakout/index.html",
  },
  {
    title: "Pong",
    slug: "pong",
    description: "Classic paddle game. Play against the computer. First to 5 wins.",
    category: "arcade",
    tags: ["classic", "paddle", "single-player"],
    thumbnail: "/assets/img/games/pong.jpg",
    difficulty: "easy",
    controls: "Arrow keys or touch buttons to move paddle",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/pong/index.html",
  },
  {
    title: "Snake",
    slug: "snake",
    description: "Guide the snake to eat food and grow longer without hitting walls or yourself.",
    category: "arcade",
    tags: ["classic", "reflex", "single-player"],
    thumbnail: "/assets/img/games/snake.jpg",
    difficulty: "easy",
    controls: "Arrow keys or WASD to change direction",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: true,
    gamePath: "/games/_src/snake/index.html",
  },

  // ========== BOARD ==========
  {
    title: "Checkers",
    slug: "checkers",
    description: "Classic checkers game. Jump over your opponent's pieces to capture them and win.",
    category: "board",
    tags: ["classic", "two-player", "strategy"],
    thumbnail: "/assets/img/games/checkers.jpg",
    difficulty: "medium",
    controls: "Click a piece, then click a valid square to move",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: false,
    gamePath: "/games/_src/checkers/index.html",
  },
  {
    title: "Connect Four",
    slug: "connect-four",
    description: "Drop discs into columns to connect four in a row before your opponent does.",
    category: "board",
    tags: ["classic", "two-player", "strategy"],
    thumbnail: "/assets/img/games/connect-four.jpg",
    difficulty: "easy",
    controls: "Click a column to drop your disc",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: false,
    gamePath: "/games/_src/connect-four/index.html",
  },
  {
    title: "Tic-Tac-Toe",
    slug: "tic-tac-toe",
    description: "Classic three-in-a-row game. Play against a friend or challenge the computer.",
    category: "board",
    tags: ["classic", "two-player", "strategy"],
    thumbnail: "/assets/img/games/tic-tac-toe.jpg",
    difficulty: "easy",
    controls: "Click or tap to place your mark",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: true,
    gamePath: "/games/_src/tic-tac-toe/index.html",
  },

  // ========== CARD ==========
  {
    title: "Solitaire",
    slug: "solitaire",
    description: "Classic Klondike solitaire. Sort all cards into four foundation piles by suit.",
    category: "card",
    tags: ["classic", "patience", "single-player"],
    thumbnail: "/assets/img/games/solitaire.jpg",
    difficulty: "medium",
    controls: "Click and drag cards to move them",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: true,
    gamePath: "/games/_src/solitaire/index.html",
  },

  // ========== PUZZLE ==========
  {
    title: "2048",
    slug: "2048",
    description: "Slide numbered tiles on a grid to combine them and reach the 2048 tile.",
    category: "puzzle",
    tags: ["numbers", "sliding", "single-player"],
    thumbnail: "/assets/img/games/2048.jpg",
    difficulty: "medium",
    controls: "Arrow keys or swipe to slide tiles",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: true,
    gamePath: "/games/_src/2048/index.html",
  },
  {
    title: "Memory Match",
    slug: "memory-match",
    description: "Flip cards to find matching pairs. Track your moves and time.",
    category: "puzzle",
    tags: ["memory", "cards", "single-player"],
    thumbnail: "/assets/img/games/memory-match.jpg",
    difficulty: "easy",
    controls: "Click or tap cards to flip them",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/memory-match/index.html",
  },
  {
    title: "Minesweeper",
    slug: "minesweeper",
    description: "Reveal squares on a grid without detonating hidden mines. Use logic to survive.",
    category: "puzzle",
    tags: ["classic", "logic", "single-player"],
    thumbnail: "/assets/img/games/minesweeper.jpg",
    difficulty: "medium",
    controls: "Left click to reveal, right click to flag",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: false,
    gamePath: "/games/_src/minesweeper/index.html",
  },
  {
    title: "Simon Says",
    slug: "simon-says",
    description: "Watch the color sequence, then repeat it. Each round adds one more step.",
    category: "puzzle",
    tags: ["memory", "sequence", "single-player"],
    thumbnail: "/assets/img/games/simon-says.jpg",
    difficulty: "easy",
    controls: "Click or tap the colored buttons",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/simon-says/index.html",
  },
  {
    title: "Sudoku",
    slug: "sudoku",
    description: "Fill the 9x9 grid so every row, column, and box contains 1 through 9.",
    category: "puzzle",
    tags: ["logic", "numbers", "single-player"],
    thumbnail: "/assets/img/games/sudoku.jpg",
    difficulty: "hard",
    controls: "Click a cell and type a number, or use the number pad",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: true,
    gamePath: "/games/_src/sudoku/index.html",
  },
  {
    title: "Tetris Clone",
    slug: "tetris-clone",
    description: "Classic falling blocks puzzle game. Clear lines to score points and level up.",
    category: "puzzle",
    tags: ["classic", "falling-blocks", "single-player"],
    thumbnail: "/assets/img/games/tetris-clone.jpg",
    difficulty: "easy",
    controls: "Arrow keys to move, Up to rotate, Space to hard drop",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: true,
    gamePath: "/games/_src/tetris-clone/index.html",
  },

  // ========== WORD ==========
  {
    title: "Hangman",
    slug: "hangman",
    description: "Guess the word one letter at a time before the hangman is complete.",
    category: "word",
    tags: ["classic", "guessing", "single-player"],
    thumbnail: "/assets/img/games/hangman.jpg",
    difficulty: "easy",
    controls: "Click letters or type on keyboard",
    mobileSupport: true,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/hangman/index.html",
  },
  {
    title: "Typing Speed",
    slug: "typing-speed",
    description: "Type as many words as you can in 60 seconds. Tracks WPM and accuracy.",
    category: "word",
    tags: ["typing", "timed", "single-player"],
    thumbnail: "/assets/img/games/typing-speed.jpg",
    difficulty: "medium",
    controls: "Type the displayed words on your keyboard",
    mobileSupport: false,
    dateAdded: "2026-04-04",
    featured: false,
    gamePath: "/games/_src/typing-speed/index.html",
  },
  {
    title: "Word Scramble",
    slug: "word-scramble",
    description: "Unscramble the letters to form a valid word before time runs out.",
    category: "word",
    tags: ["vocabulary", "timed", "single-player"],
    thumbnail: "/assets/img/games/word-scramble.jpg",
    difficulty: "medium",
    controls: "Type letters on keyboard or click letter tiles",
    mobileSupport: true,
    dateAdded: "2026-04-03",
    featured: false,
    gamePath: "/games/_src/word-scramble/index.html",
  },
];
